In [3]:
## imports 
import pandas as pd
import numpy as np
import yaml
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

# comment these out if you don't have plotnine--not essential here/only used once
import matplotlib.pyplot as plt
# import plotnine
# from plotnine import *

## way to connect to mysql 
## if you need to install
## uncomment this line:
#! pip install mysql-connector-python
import mysql.connector

## function to feed path name to load
## credentials
def load_creds(path: str):
    with open(path, 'r') as stream:
        try:
            creds = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)
    return(creds)

pd.options.display.max_rows = 999
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Preliminary: define connection and read sample of data

In [5]:
## read in creds; change the path name if stored
## elsewhere
creds = load_creds("../activities/09_db_cred.yaml")

In [6]:
creds

{'practice_database': {'user': 'qss20',
  'password': 'xtPdDZHnxKMFSD5RyP',
  'port': 3306,
  'database': 'sentencing',
  'host': 'qss20-7570-db.c.dartmouth.edu'}}

In [7]:
creds['practice_database']['database']

'sentencing'

In [11]:
cnx = mysql.connector.connect(
    user=creds['practice_database']['user'],
    password = creds['practice_database']['password'],
    port = creds['practice_database']['port'],
    database = creds['practice_database']['database'],
    host = creds['practice_database']['host']
)
cursor = cnx.cursor(buffered=True)
cnx

In [10]:
q = """
SELECT
    * 
FROM caseinit
LIMIT 5
"""
pd.read_sql_query(q, cnx)

,CASE_ID,CASE_PARTICIPANT_ID,RECEIVED_DATE,OFFENSE_CATEGORY,PRIMARY_CHARGE_FLAG,CHARGE_ID,CHARGE_VERSION_ID,DISPOSITION_CHARGED_OFFENSE_TITLE,CHARGE_COUNT,DISPOSITION_DATE,...,INCIDENT_END_DATE,LAW_ENFORCEMENT_AGENCY,LAW_ENFORCEMENT_UNIT,ARREST_DATE,FELONY_REVIEW_DATE,FELONY_REVIEW_RESULT,ARRAIGNMENT_DATE,UPDATED_OFFENSE_CATEGORY,is_in_diversion,in_chicago
0,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242195814523,155656315869,FIRST DEGREE MURDER,2,12/17/2014 12:00:00 AM,...,,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None
1,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242198287388,131513547452,HOME INVASION,14,12/17/2014 12:00:00 AM,...,,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None
2,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242351605056,176626576281,FIRST DEGREE MURDER,4,12/17/2014 12:00:00 AM,...,,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None
3,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242352841488,176617824190,FIRST DEGREE MURDER,5,12/17/2014 12:00:00 AM,...,,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None
4,198055620664,85937621020,08/15/1984 12:00:00 AM,PROMIS Conversion,False,1242356550787,131238606761,HOME INVASION,13,12/17/2014 12:00:00 AM,...,,CHICAGO POLICE DEPT,,08/15/1984 12:00:00 AM,08/15/1984 12:00:00 AM,Charge(S) Approved,09/21/1984 12:00:00 AM,PROMIS Conversion,False,None

# Activity 1

1. Create a new column -- `in_chicago` when pulling from the `caseinit` table that takes on the value of "YES" if INCIDENT_CITY = Chicago; "NO" otherwise (which represents incidents in Cook County suburbs outside the city limits);  and pull the table. Use `crosstabs` to confirm that this worked
2. Repeat step 1 but also filter out blank strings (`INCIDENT_CITY` == "")
3. Use `where` to row filter to initiations in Chicago and use group by to find the count of cases diverted and not diverted (`is_in_diversion`); pull the table with those counts
4. Modify the query in step 3 to find the proportion of cases in chicago diverted (hint you made need to use case when in a subquery)
5. Modify the query in step 4 to find the proportion of cases in chicago versus cases not in chicago sent to diversion

In [29]:
# your code here 1
q = """
SELECT
    INCIDENT_CITY,
    CASE 
        WHEN INCIDENT_CITY = 'Chicago' THEN 'YES'
        ELSE 'NO'
    END AS in_chicago1
FROM caseinit;
"""
incidents = pd.read_sql_query(q, cnx)

# crosstab
crosstab = pd.crosstab(incidents['INCIDENT_CITY'], incidents['in_chicago1'])
print(crosstab)

in_chicago1               NO     YES
INCIDENT_CITY
                       20557       0
Addison                    2       0
Albers                     1       0
Algonquin                  3       0
Alsip                    568       0
Antioch                    2       0
Arlington Heights       1291       0
Aurora                     3       0
Barrington               136       0
Barrington Hills          16       0
Bartlett                 241       0
Bedford Park             335       0
Beecher                    1       0
Bellwood                 848       0
Bensenville                3       0
Berkeley                 160       0
Berwyn                  2152       0
Bloomingdale               1       0
Bloomington                1       0
Blue Island             1192       0
Bluff Springs              1       0
Bolingbrook                5       0
Bourbonnais                1       0
Braidwood                  1       0
Bridgeview               704       0
Brighton                   1       0
Broadview                558       0
Brookfield               338       0
Brookport                  1       0
Buffalo Grove            245       0
Burbank                  575       0
Burlington                 1       0
Burnham                  238       0
Burr Ridge                57       0
Calumet City            1972       0
Calumet Park             434       0
Cambria                    1       0
Canton                     1       0
Cary                       1       0
Cedar Lake                 2       0
Channahon                  2       0
Chestnut                   1       0
Chicago                    0  173573
Chicago Heights         2039       0
Chicago Ridge            472       0
Cicero                  4263       0
Cimic                      1       0
Country Club Hills       529       0
Countryside              223       0
Crestwood                374       0
Crete                      2       0
Darien                     1       0
Deerfield                 59       0
DesPlaines              1374       0
Dixmoor                   98       0
Dixon                      1       0
Dolton                  1209       0
Downers Grove              4       0
East Chicago               2       0
East Hazel Crest         174       0
Elgin                    499       0
Elk Grove Village        767       0
Elkhart                    1       0
Elmhurst                  24       0
Elmwood                    1       0
Elmwood Park             660       0
Evanston                1772       0
Evansville                 1       0
Evergreen Park          1414       0
Ewing                      3       0
Flossmoor                297       0
Ford Heights             488       0
Forest City                1       0
Forest Park             1502       0
Forest View               56       0
Frankfort                  1       0
Franklin Park            734       0
Glen Ellyn                 2       0
Glencoe                  118       0
Glendale Heights           1       0
Glenview                 694       0
Glenwood                 258       0
Golf                       1       0
Griffith                   1       0
Gurnee                     6       0
Halstead                   1       0
Hammond                    5       0
Hanover                    1       0
Hanover Park             847       0
Harvey                  2080       0
Harwood Heights          264       0
Hazel Crest              399       0
Hickory Hills            311       0
Highland Park              1       0
Highwood                   1       0
Hillside                 526       0
Hinckley                   1       0
Hines                     45       0
Hinsdale                  23       0
Hobart                     1       0
Hodgkins                 395       0
Hoffman                    1       0
Hoffman Estates         1048       0
Homer Glen                 2       0
Hometown                  86       0
Homewood                1126       0
Indian Head Park          43       0
Ingleside                  2       0
Inverness                 11       0
Itasca                     1       0
Jefferson Park             9       0
Joliet                     4       0
Justice                  443       0
Kenilworth                14       0
LaGrange                 186       0
LaGrange Highlands         8       0
LaGrange Park             79       0
Lake Barrington            1       0
Lake Bluff                 2       0
Lake In The Hills          1       0
Lake Zurich                2       0
Lansing                 1072       0
Lemont                   296       0
Lincolnwood              352       0
Lombard                    1       0
Lynwood                  260       0
Lyons                    287       0
Markham                  885       0
Marseilles                 2       0
Matteson                1065       0
Maywood                 1526       0
McCook                    65       0
Melrose Park            1226       0
Merrionette Park          47       0
Midlothian               568       0
Minneapolis                1       0
Mokena                     1       0
Monee                      1       0
Morton                     2       0
Morton Grove             386       0
Mount Greenwood           10       0
Mount Prospect          1195       0
Mundelein                  1       0
Munster                    1       0
Naperville                 4       0
New Lenox                  2       0
Niles                    799       0
Norridge                 477       0
North Chicago              1       0
North Riverside          879       0
Northbrook               608       0
Northfield                83       0
Northlake                635       0
Oak Brook                  9       0
Oak Brook Mall             1       0
Oak Forest               439       0
Oak Lawn                1775       0
Oak Park                1749       0
Oakbrook Terrace           1       0
Olympia FIELDS             2       0
Olympia Fields           149       0
Orland Hills             115       0
Orland Park             1870       0
Oswego                     1       0
Palatine                1359       0
Palos Heights            181       0
Palos Hills              218       0
Palos Park                90       0
Park City                  5       0
Park Forest              908       0
Park Ridge               329       0
Phoenix                   73       0
Pinckneyville              1       0
Plato Center               1       0
Pontiac                    3       0
Portage                    1       0
Posen                    345       0
Prospect Heights         436       0
Ransom                     1       0
Richton Park             347       0
River Forest             753       0
River Grove              287       0
Riverdale                766       0
Riverside                358       0
Robbins                  289       0
Rockford                   3       0
Rolling Meadows          539       0
Roselle                   43       0
Rosemont                 760       0
Round Lake                 2       0
Saint Charles              3       0
Sauget                     1       0
Sauk Village             875       0
Savanna                    1       0
Schaumburg              1850       0
Schererville               1       0
Schiller Park            589       0
Sheridan                   1       0
Skokie                  1532       0
South Barrington         191       0
South Bend                 1       0
South Chicago Heights    145       0
South Holland            621       0
Steger                    91       0
Steward                    1       0
Stickney                 167       0
Stone Park               193       0
Streamwood              1198       0
Summit                   438       0
Summit Argo                4       0
Thornton                  42       0
Tinley Park              735       0
University Park           10       0
Vernon Hills               1       0
Waukegan                   5       0
West Chicago               1       0
West Dundee                1       0
Westchester              341       0
Western Springs           52       0
Westmont                   1       0
Wheaton                    4       0
Wheeling                1094       0
Willow Springs            82       0
Willowbrook                2       0
Wilmette                 333       0
Winnetka                 129       0
Wood Dale                  3       0
Woodstock                  1       0
Worth                    284       0

In [18]:
# your code here 2
q = """
SELECT
    INCIDENT_CITY,
    CASE 
        WHEN INCIDENT_CITY = 'Chicago' THEN 'YES'
        ELSE 'NO'
    END AS in_chicago1
FROM caseinit;
"""
pd.read_sql_query(q, cnx)

             INCIDENT_CITY in_chicago  incident_count
0                  Addison         NO               2
1                   Albers         NO               1
2                Algonquin         NO               3
3                    Alsip         NO             568
4                  Antioch         NO               2
5        Arlington Heights         NO            1291
6                   Aurora         NO               3
7               Barrington         NO             136
8         Barrington Hills         NO              16
9                 Bartlett         NO             241
10            Bedford Park         NO             335
11                 Beecher         NO               1
12                Bellwood         NO             848
13             Bensenville         NO               3
14                Berkeley         NO             160
15                  Berwyn         NO            2152
16            Bloomingdale         NO               1
17             Bloomington         NO               1
18             Blue Island         NO            1192
19           Bluff Springs         NO               1
20             Bolingbrook         NO               5
21             Bourbonnais         NO               1
22               Braidwood         NO               1
23              Bridgeview         NO             704
24                Brighton         NO               1
25               Broadview         NO             558
26              Brookfield         NO             338
27               Brookport         NO               1
28           Buffalo Grove         NO             245
29                 Burbank         NO             575
30              Burlington         NO               1
31                 Burnham         NO             238
32              Burr Ridge         NO              57
33            Calumet City         NO            1972
34            Calumet Park         NO             434
35                 Cambria         NO               1
36                  Canton         NO               1
37                    Cary         NO               1
38              Cedar Lake         NO               2
39               Channahon         NO               2
40                Chestnut         NO               1
41                 Chicago        YES          173573
42         Chicago Heights         NO            2039
43           Chicago Ridge         NO             472
44                  Cicero         NO            4263
45                   Cimic         NO               1
46      Country Club Hills         NO             529
47             Countryside         NO             223
48               Crestwood         NO             374
49                   Crete         NO               2
50                  Darien         NO               1
51               Deerfield         NO              59
52              DesPlaines         NO            1374
53                 Dixmoor         NO              98
54                   Dixon         NO               1
55                  Dolton         NO            1209
56           Downers Grove         NO               4
57            East Chicago         NO               2
58        East Hazel Crest         NO             174
59                   Elgin         NO             499
60       Elk Grove Village         NO             767
61                 Elkhart         NO               1
62                Elmhurst         NO              24
63                 Elmwood         NO               1
64            Elmwood Park         NO             660
65                Evanston         NO            1772
66              Evansville         NO               1
67          Evergreen Park         NO            1414
68                   Ewing         NO               3
69               Flossmoor         NO             297
70            Ford Heights         NO             488
71             Forest City         NO               1
72             Forest Park         NO            1502
73             Forest View         NO              56
74               Frankfort         NO               1
75           Franklin Park         NO             734
76              Glen Ellyn         NO               2
77                 Glencoe         NO             118
78        Glendale Heights         NO               1
79                Glenview         NO             694
80                Glenwood         NO             258
81                    Golf         NO               1
82                Griffith         NO               1
83                  Gurnee         NO               6
84                Halstead         NO               1
85                 Hammond         NO               5
86                 Hanover         NO               1
87            Hanover Park         NO             847
88                  Harvey         NO            2080
89         Harwood Heights         NO             264
90             Hazel Crest         NO             399
91           Hickory Hills         NO             311
92           Highland Park         NO               1
93                Highwood         NO               1
94                Hillside         NO             526
95                Hinckley         NO               1
96                   Hines         NO              45
97                Hinsdale         NO              23
98                  Hobart         NO               1
99                Hodgkins         NO             395
100                Hoffman         NO               1
101        Hoffman Estates         NO            1048
102             Homer Glen         NO               2
103               Hometown         NO              86
104               Homewood         NO            1126
105       Indian Head Park         NO              43
106              Ingleside         NO               2
107              Inverness         NO              11
108                 Itasca         NO               1
109         Jefferson Park         NO               9
110                 Joliet         NO               4
111                Justice         NO             443
112             Kenilworth         NO              14
113               LaGrange         NO             186
114     LaGrange Highlands         NO               8
115          LaGrange Park         NO              79
116        Lake Barrington         NO               1
117             Lake Bluff         NO               2
118      Lake In The Hills         NO               1
119            Lake Zurich         NO               2
120                Lansing         NO            1072
121                 Lemont         NO             296
122            Lincolnwood         NO             352
123                Lombard         NO               1
124                Lynwood         NO             260
125                  Lyons         NO             287
126                Markham         NO             885
127             Marseilles         NO               2
128               Matteson         NO            1065
129                Maywood         NO            1526
130                 McCook         NO              65
131           Melrose Park         NO            1226
132       Merrionette Park         NO              47
133             Midlothian         NO             568
134            Minneapolis         NO               1
135                 Mokena         NO               1
136                  Monee         NO               1
137                 Morton         NO               2
138           Morton Grove         NO             386
139        Mount Greenwood         NO              10
140         Mount Prospect         NO            1195
141              Mundelein         NO               1
142                Munster         NO               1
143             Naperville         NO               4
144              New Lenox         NO               2
145                  Niles         NO             799
146               Norridge         NO             477
147          North Chicago         NO               1
148        North Riverside         NO             879
149             Northbrook         NO             608
150             Northfield         NO              83
151              Northlake         NO             635
152              Oak Brook         NO               9
153         Oak Brook Mall         NO               1
154             Oak Forest         NO             439
155               Oak Lawn         NO            1775
156               Oak Park         NO            1749
157       Oakbrook Terrace         NO               1
158         Olympia Fields         NO             151
159           Orland Hills         NO             115
160            Orland Park         NO            1870
161                 Oswego         NO               1
162               Palatine         NO            1359
163          Palos Heights         NO             181
164            Palos Hills         NO             218
165             Palos Park         NO              90
166              Park City         NO               5
167            Park Forest         NO             908
168             Park Ridge         NO             329
169                Phoenix         NO              73
170          Pinckneyville         NO               1
171           Plato Center         NO               1
172                Pontiac         NO               3
173                Portage         NO               1
174                  Posen         NO             345
175       Prospect Heights         NO             436
176                 Ransom         NO               1
177           Richton Park         NO             347
178           River Forest         NO             753
179            River Grove         NO             287
180              Riverdale         NO             766
181              Riverside         NO             358
182                Robbins         NO             289
183               Rockford         NO               3
184        Rolling Meadows         NO             539
185                Roselle         NO              43
186               Rosemont         NO             760
187             Round Lake         NO               2
188          Saint Charles         NO               3
189                 Sauget         NO               1
190           Sauk Village         NO             875
191                Savanna         NO               1
192             Schaumburg         NO            1850
193           Schererville         NO               1
194          Schiller Park         NO             589
195               Sheridan         NO               1
196                 Skokie         NO            1532
197       South Barrington         NO             191
198             South Bend         NO               1
199  South Chicago Heights         NO             145
200          South Holland         NO             621
201                 Steger         NO              91
202                Steward         NO               1
203               Stickney         NO             167
204             Stone Park         NO             193
205             Streamwood         NO            1198
206                 Summit         NO             438
207            Summit Argo         NO               4
208               Thornton         NO              42
209            Tinley Park         NO             735
210        University Park         NO              10
211           Vernon Hills         NO               1
212               Waukegan         NO               5
213           West Chicago         NO               1
214            West Dundee         NO               1
215            Westchester         NO             341
216        Western Springs         NO              52
217               Westmont         NO               1
218                Wheaton         NO               4
219               Wheeling         NO            1094
220         Willow Springs         NO              82
221            Willowbrook         NO               2
222               Wilmette         NO             333
223               Winnetka         NO             129
224              Wood Dale         NO               3
225              Woodstock         NO               1
226                  Worth         NO             284

In [ ]:
# your code here 3

In [ ]:
# your code here 4

In [ ]:
# your code here 5

# Activity 2 

1. Use the following crosswalk and the `CASE` variable in the `divert` table to create a new variable `DIVERSION_PROGRAM_TEXT` that spells out the diversion programs
    - DC: Drug Court

    - DDPP: Drug Deferred Prosecution

    - DS: Drug School

    - RJCC: Restorative Justice

    - MHC: Mental Health Court

    - VC: Veteran Court

2. Build on the query from step 1 to filter to Narcotics as the `UPDATED_OFFENSE_CATEGORY` and Black or White defendants (based on race in the diversions table) (hint: you'll need to join with the caseinit table based on case_id and case_participant_id, you can do a inner join to keep only those diverted). Select the case_id, case_participant_id, case, race, and diversion_program_text columns

In [ ]:
# your code here 1

In [ ]:
# your code here 2